name: Continuous Integration Pipeline

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
        - dev
      types:
        - opened
        - reopened
        - synchronize
        - ready_for_review  

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check format
        run: |
          black . --check --verbose --exclude .git
